### ISSUE TITLE
New features and various thoughts

### ISSUE THREAD

**Issue by frederikhors** [go-pg/pg#1769]
In my daily use of `go-pg` I have noticed a few things that I would like to learn more about. I list them here by way of todo. I will take care of closing the issue as soon as I have deepened them all.

- [x] <s>DOCS: I think the example [here](https://pg.uptrace.dev/queries/#update) is misleading:</s> [@vmihailenco's answer here.](https://github.com/go-pg/pg/issues/1769#issuecomment-723117694)
  <s>
  ```go
  err := db.Model(book).Update()
  ```

  Can we clarify it better? Because the below code is wrong for `go-pg`:

  ```go
  var book Book
  book.ID = 1
  err := db.Model(book).Update()
  ```

  The error is: `pg: Model(non-pointer Book)`</s>

- [x] <s>GITHUB: How about adding the "Discussions" tab here in Github so we can talk about something other than "issues"?</s> [@vmihailenco's answer here.](https://github.com/go-pg/pg/issues/1769#issuecomment-723117694)

  <s>Like this: https://github.com/FormidableLabs/urql/discussions.

- [x] LOGGER: Using the code [here](https://pg.uptrace.dev/faq/#how-to-view-queries-this-library-generates) the logger works. But I have lines with no space between like this: [@vmihailenco's answer here.](https://github.com/go-pg/pg/issues/1769#issuecomment-723117694)

  ```
  SELECT 1
  SELECT 1
  ```

  When the queries are long it gets a little tricky to read them and figure out which one you are looking for.

  Can we switch to default have one empty line between? Like this:

  ```
  SELECT 1

  SELECT 1
  ```
  </s>

- [x] <s>DOCS: Maybe we miss a "recipe" or a FAQ with suggestions/advice on the indexes to be created for the most common situations (for example relations).</s> [@vmihailenco's answer here.](https://github.com/go-pg/pg/issues/1769#issuecomment-719571279)

  <s>_It would also be useful for people like me who are learning Postgres using `go-pg` at the same time._</s>

- [x] <s>FUTURE: In some projects my colleagues have chosen Gorm 2. I remain faithful to `go-pg` which is better IMO in many ways. But I have noticed one thing is much more comfortable.</s> [@vmihailenco's answer here.](https://github.com/go-pg/pg/issues/1769#issuecomment-719571279)

  <s>What do you think for the future to go from these:

   ```go
   db.Model(book).Where("id = ?", 1).Select()
   db.Model(book).Where("id = ?", 1).Update()
   db.Model(book).Where("id = ?", 1).Delete()
   db.Model(book).WherePK().Select()
   ```

   to the following?

   ```go
   db.Select(book, 1)
   db.Update(book, 1)
   db.Delete(book, 1)
   ```

   or better:

   ```go
   // If Book's ID is 1
   db.Select(&book)
   db.Update(&book)
   db.Delete(&book)
   ```
   </s>

- [x] <s>FUTURE: Confortable multi-tenancy. Already [described here](https://github.com/go-pg/pg/issues/1363#issuecomment-718161021).</s> [@vmihailenco's answer here.](https://github.com/go-pg/pg/issues/1769#issuecomment-719571279)

  <s>One ORM-native way to solve this problem would be the fulfilled wish of every man on this earth. :smile:

  - [x] But at least, can we have something custom I can create like the following?

      ```go
        db.AccountableModel()...
      ```

  - [x] Can we use something like Gorm's callbacks: https://gorm.io/docs/write_plugins.html#Callbacks?</s>

---

Thanks for your commitment.
**Your work is amazing!**

**Comment by vmihailenco** [comment]
```go
// If Book's ID is 1
db.Select(&book)
db.Update(&book)
db.Delete(&book)
```

This used to work in v8 and was gradually removed in v9 and v10. It is rarely used in practice and creates some confusion, e.g. what to do when `id=0` and some people mis-understand how it works.

Looking at the https://gorm.io/docs/write_plugins.html#Callbacks I am not sure that I like the example there. And I am not sure that multi-tenancy is something that should be supported out-of-the-box. And that you need ORM to create an index.

I appreciate you effort but I don't think it is very productive and that creating lists like this one is the right way forward.

**Comment by frederikhors** [comment]
I updated the first post.

1. DOCS: Is that example right?

1. GITHUB: Are you going to add that "Discussions" tab?

1. LOGGER: I created a PR for that: https://github.com/go-pg/pg/pull/1775

**Comment by vmihailenco** [comment]
Hey,

>DOCS: Is that example right?

I've fixed the example - thanks for pointing that out.

>GITHUB: Are you going to add that "Discussions" tab?

AFAIK that is not a publicly available feature. There is nothing I can enable.

>LOGGER: I created a PR for that: #1775

Merged - thanks.

**Comment by frederikhors** [comment]
I think people is asking for it [here](
https://github.community/t/can-one-apply-for-github-discussions-beta/121120/411) but it's crazy to post there. We'll wait for it to come.

Thanks for now.
